import { ErrorResponseSchema } from './error.schema';

export const TherapyBodySchema = {
  type: 'object',
  additionalProperties: false,
  required: ['goal', 'genre', 'durationSeconds'],
  properties: {
    goal: {
      type: 'string',
      enum: [
        'pain_relief',
        'emotion_relief',
        'deep_sleep',
        'anti_aging',
        'healing',
        'rem_sleep',
        'deep_relaxation',
        'meditation',
        'creativity',
        'relaxed_focus',
        'stress_reduction',
        'positive_thinking',
        'fast_learning',
        'focused_attention',
        'cognitive_thinking',
        'problem_solving',
        'active_lifestyle',
        'high_cognition',
        'memory_recall',
        'peak_awareness',
      ],
    },
    genre: {
      type: 'string',
      minLength: 1,
      maxLength: 100,
    },
    bodyArea: {
      type: 'string',
      enum: [
        'abdominal',
        'back',
        'chest',
        'chronic',
        'groin',
        'head',
        'hip',
        'joint',
        'knee',
        'leg',
        'muscle',
        'nerve',
        'painful_sex',
        'penis_pain',
        'period',
        'shoulder',
      ],
    },
    emotion: {
      type: 'string',
      enum: [
        'anger',
        'guilt',
        'shame',
        'depression',
        'annoyance',
        'hurt',
        'hostility',
        'fear',
        'anxiety',
        'loneliness',
        'boredom',
        'embarrassment',
        'envy',
        'contempt',
        'despair',
        'sadness',
        'disgust',
        'disappointment',
        'frustration',
        'hate',
        'jealousy',
        'pride',
        'surprise',
        'confusion',
      ],
    },
    culturalMode: {
      type: 'string',
      enum: ['chinese_five_element', 'indian_raga', 'ottoman_maqam'],
    },
    durationSeconds: {
      type: 'integer',
      minimum: 1,
    },
    intensity: {
      type: 'string',
      enum: ['soft', 'medium', 'high'],
    },
  },
} as const;

export const TherapySuccessResponseSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['id', 'status', 'downloadUrl', 'format', 'expiresIn', 'metadata'],
  properties: {
    id: { type: 'string' },
    status: { type: 'string', const: 'completed' },
    downloadUrl: { type: 'string' },
    format: { type: 'string', const: 'mp3' },
    expiresIn: { type: 'integer', minimum: 1 },
    metadata: {
      type: 'object',
      additionalProperties: false,
      required: [
        'goal',
        'genre',
        'duration',
        'intensity',
        'frequency',
        'provider',
        'plan',
        'watermarked',
        'commercialLicense',
      ],
      properties: {
        goal: { type: 'string' },
        genre: { type: 'string' },
        bodyArea: { type: 'string' },
        emotion: { type: 'string' },
        duration: { type: 'integer' },
        intensity: { type: 'string', enum: ['soft', 'medium', 'high'] },
        frequency: {
          type: 'object',
          additionalProperties: false,
          required: ['band', 'hz', 'label'],
          properties: {
            band: { type: 'string', enum: ['delta', 'theta', 'alpha', 'beta', 'gamma'] },
            hz: { type: 'number' },
            solfeggioHz: { type: 'number' },
            label: { type: 'string' },
          },
        },
        culturalMode: {
          type: 'string',
          enum: ['chinese_five_element', 'indian_raga', 'ottoman_maqam'],
        },
        provider: { type: 'string' },
        plan: { type: 'string', enum: ['free', 'basic', 'pro', 'ultra'] },
        watermarked: { type: 'boolean' },
        commercialLicense: { type: 'boolean' },
      },
    },
    downloadUrlWav: { type: 'string' },
    formatWav: { type: 'string', const: 'wav' },
  },
} as const;

export const TherapySchema = {
  body: TherapyBodySchema,
  response: {
    200: TherapySuccessResponseSchema,
    '4xx': ErrorResponseSchema,
    '5xx': ErrorResponseSchema,
  },
} as const;
